"""NSE stock universe: 500+ tickers organized by index membership."""

from typing import Dict, List, Tuple

# ── Nifty 50 ─────────────────────────────────────────────────────────────────
NIFTY_50: List[str] = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE", "BHARTIARTL", "BPCL",
    "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY",
    "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK",
    "INFY", "ITC", "JSWSTEEL", "KOTAKBANK", "LT",
    "M&M", "MARUTI", "NESTLEIND", "NTPC", "ONGC",
    "POWERGRID", "RELIANCE", "SBILIFE", "SBIN", "SHREECEM",
    "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TCS",
    "TECHM", "TITAN", "ULTRACEMCO", "UPL", "WIPRO",
]

# ── Nifty Next 50 ─────────────────────────────────────────────────────────────
NIFTY_NEXT_50: List[str] = [
    "ABB", "ABBOTINDIA", "AMBUJACEM", "AUROPHARMA", "BANDHANBNK",
    "BERGEPAINT", "BIOCON", "BOSCHLTD", "CHOLAFIN", "COLPAL",
    "DABUR", "DLF", "GAIL", "GODREJCP", "GODREJPROP",
    "HAVELLS", "ICICIGI", "ICICIPRULI", "INDIGO", "INDUSTOWER",
    "IOC", "JINDALSTEL", "JUBLFOOD", "LUPIN", "MARICO",
    "MCDOWELL-N", "MFSL", "MUTHOOTFIN", "NAUKRI", "NMDC",
    "OFSS", "PAGEIND", "PIIND", "PIDILITIND", "RECLTD",
    "SAIL", "SIEMENS", "SRF", "TORNTPHARM", "TRENT",
    "TVSMOTOR", "UBL", "VEDL", "VOLTAS", "ADANIGREEN",
    "ADANITRANS", "BALKRISIND", "ZOMATO", "ZEEL", "WHIRLPOOL",
]

# ── Nifty Midcap 150 ──────────────────────────────────────────────────────────
NIFTY_MIDCAP_150: List[str] = [
    "AAVAS", "ABCAPITAL", "ABFRL", "ACC", "AFFLE",
    "AJANTPHARM", "ALKEM", "APLLTD", "ASTRAL", "ATUL",
    "AUBANK", "BAJAJHFL", "BATAINDIA", "BHARATFORG", "BLUESTARCO",
    "BSOFT", "CAMS", "CANFINHOME", "CDSL", "CESC",
    "CHAMBLFERT", "CLEAN", "CONCOR", "COROMANDEL", "CROMPTON",
    "CUMMINSIND", "DCMSHRIRAM", "DEEPAKNTR", "DELTACORP", "DIXON",
    "EDELWEISS", "ELGIEQUIP", "EMAMILTD", "ENDURANCE", "ENGINERSIN",
    "EQUITASBNK", "EXIDEIND", "FEDERALBNK", "FINEORG", "FLUOROCHEM",
    "FORTIS", "GALAXYSURF", "GHCL", "GNFC", "GODREJIND",
    "GRANULES", "GSFC", "GSPL", "GUJGASLTD", "HAPPSTMNDS",
    "HATSUN", "HDFCAMC", "HFCL", "HIKAL", "HINDPETRO",
    "HONAUT", "HUDCO", "IBREALEST", "IDFC", "IDFCFIRSTB",
    "IEX", "IIFL", "INDHOTEL", "INDIAMART", "INDIANB",
    "IOLCP", "IPCA", "IRCTC", "JBCHEPHARM", "JKCEMENT",
    "JKLAKSHMI", "JKPAPER", "JKTYRES", "JMFINANCIL", "JUBLINGREA",
    "KAJARIACER", "KALPATPOWR", "KANSAINER", "KEC", "KPITTECH",
    "KRBL", "LALPATHLAB", "LAURUSLABS", "LEMONTREE", "LICI",
    "LINDEINDIA", "LTTS", "LUXIND", "MANAPPURAM", "MASFIN",
    "MAXHEALTH", "METROPOLIS", "MGL", "MINDACORP", "MPHASIS",
    "NATCOPHARM", "NAVINFLUOR", "NESCO", "NILKAMAL", "OLECTRA",
    "ORIENTCEM", "PATELENG", "PCBL", "PERSISTENT", "PFIZER",
    "PHOENIXLTD", "POLYCAB", "POONAWALLA", "QUESS", "RADICO",
    "RAILTEL", "RAIN", "RALLIS", "RATNAMANI", "RAYMOND",
    "REDINGTON", "RELAXO", "RITES", "ROUTE", "SAPPHIRE",
    "SCHAEFFLER", "SEQUENT", "SKFINDIA", "SOBHA", "SOLARINDS",
    "SPARC", "SPANDANA", "STOVEKRAFT", "SUDARSCHEM", "SUMICHEM",
    "SUNTV", "SUPRAJIT", "SUPREMEIND", "SYNGENE", "TASTYBITE",
    "TATACHEM", "TATACOMM", "TATAINVEST", "TEAMLEASE", "THERMAX",
    "TIMKEN", "TTKPRESTIG", "TVSSRICHAK", "UJJIVAN", "UNIONBANK",
    "USHAMART", "VAIBHAVGBL", "VARROC", "VGUARD", "VMART",
    "VSTIND", "WOCKPHARMA", "YESBANK", "ZYDUSLIFE", "SOLARA",
    "MAITHANALL", "POLYMED", "RPGLIFE", "SANOFI", "MIDHANI",
    "APOLLOTYRE", "APCOTEX", "CERA", "CYIENT", "DCBBANK",
    "GLENMARK", "GRINDWELL", "JYOTHYLAB", "KPRMILL", "MINDA",
    "MOTILALOFS", "NAVNETEDUL", "NEOGEN", "NIITLTD", "PRAJIND",
    "PRINCEPIPE", "RBLBANK", "VIMTALABS", "INDIGOPNTS", "SUVENPHAR",
]

# ── Nifty Smallcap 250 ────────────────────────────────────────────────────────
NIFTY_SMALLCAP_250: List[str] = [
    "AARTIDRUGS", "AARTIIND", "ACCELYA", "AEGISCHEM", "AIAENG",
    "AJMERA", "AKZOINDIA", "ALEMBICLTD", "ALICON", "ALKYLAMINE",
    "ALLCARGO", "AMBER", "ANGELONE", "APARINDS", "ARVIND",
    "ASHOKA", "AVANTIFEED", "AVTNPL", "BAJAJCON", "BALAXI",
    "BALAMINES", "BALMLAWRIE", "BEML", "CAMLINFINE", "CAPLIPOINT",
    "CARBORUNIV", "CARERATING", "CASTROLIND", "CEATLTD", "CENTURYPLY",
    "CENTURYTEX", "CHEMCON", "CHENNPETRO", "CIGNITITEC", "CMSINFO",
    "COCHINSHIP", "COLORCHEMS", "COSMOFILMS", "CRAFTSMAN", "DATAPATTNS",
    "DATAMATICS", "DBCORP", "DEEPAKFERT", "DFMFOODS", "DHANLAXMI",
    "DREDGECORP", "DYNAMATECH", "EASEMYTRIP", "ELGI", "EMKAY",
    "EMMBI", "ENIL", "ESABINDIA", "FILATEX", "FORCEMOT",
    "GABRIEL", "GANESHHOUC", "GARFIBRES", "GEECEE", "GENUSPAPER",
    "GLOBUSSPR", "GODFRYPHLP", "GOLDIAM", "GOODLUCK", "GREAVESCOT",
    "GREENPANEL", "GUFICBIO", "GULFOILLUB", "HARDCASTLE", "HBLPOWER",
    "HERANBA", "HIMATSEIDE", "HMVL", "HOMEFIRST", "HSIL",
    "IGARASHI", "IGPL", "IIFLSEC", "IMFA", "INDORAMA",
    "INFIBEAM", "IONEXCHANG", "IRCON", "ISGEC", "J&KBANK",
    "JAGRAN", "JAIBALAJI", "JAL", "JASH", "JAYAGROGN",
    "JOCIL", "JPPOWER", "JUSTDIAL", "KALYANKJIL", "KELLTONTEC",
    "KIRIIND", "KIRLOSBROS", "KITEX", "KNRCON", "KOLTEPATIL",
    "KRSNAA", "LAOPALA", "LATENTVIEW", "LICHSGFIN", "LINC",
    "LXCHEM", "M&MFIN", "MADRASFERT", "MAHLIFE", "MAHSCOOTER",
    "MANINFRA", "MAPMYINDIA", "MARKSANS", "MASTEK", "MEDPLUS",
    "MENONBE", "METROBRAND", "MFL", "MOIL", "MOLDTKPAC",
    "MPSLTD", "MRF", "MRPL", "MUKANDLTD", "NACLIND",
    "NAHARPOLY", "NALCO", "NBCC", "NETWEB", "NFL",
    "NGLFINECHEM", "NIITLTD", "NLCINDIA", "NUCLEUS", "OCCL",
    "ONMOBILE", "OPTIEMUS", "PANAMAPET", "PARAGMILK", "PASHUPATI",
    "PAUSHAKLTD", "PCJEWELLER", "PLASTIBLENDS", "POLYPLEX", "PRAJ",
    "PRECOT", "PRESTIGE", "PRICOL", "PRISM", "QUICKHEAL",
    "RADCON", "RAILVIKAS", "RCF", "RELIGARE", "RENUKA",
    "RICOAUTO", "RKFORGE", "RUPA", "RUSHIL", "SAFARI",
    "SAREGAMA", "SAVITA", "SHAKTIPUMP", "SHANKARA", "SHARDACROP",
    "SHAREINDIA", "SHILPAMED", "SHIVALIK", "SHOPERSTOP", "SKIPPER",
    "SMARTLINK", "SOLEX", "SPENCERS", "SPTL", "STLTECH",
    "SUBROS", "SURYODAY", "SYMPHONY", "SYRMA", "TANLA",
    "TBOTECH", "THYROCARE", "TITAGARH", "TIPSINDLTD", "TRITON",
    "TVSHLTD", "UCAL", "UFLEX", "UNITDSPR", "V2RETAIL",
    "VINAYCHEM", "WABCOINDIA", "WELSPUNIND", "WESTLIFE", "WONDERLA",
    "XCHANGING", "YATHARTH", "YUKEN", "ZODIAC", "ZUARI",
    "ASTERDM", "INOXWIND", "JNKIND", "KAJARIACER", "LASA",
    "NIPSEYLIFE", "OISL", "PARABDRUGS", "SADHBHAV", "TRONOX",
    "KSCL", "GRINFRA", "SAFARI", "SBCL", "SWSOLAR",
    "RPSGVENT", "RTNINDIA", "RUBYMILLS", "RUCHINFRA", "SAGARDEEP",
    "SAHYADRI", "SANDESH", "SANGAMIND", "SARLAPOLY", "SATIA",
    "SAURASHCEM", "SBFC", "SELAN", "SHANTIGEAR", "SHIVAM",
    "SHOPERSTOP", "SHRIRAMPPS", "SHRIRAMCIT", "SILINV", "SKMILEVENTH",
    "SMSPHARMA", "SOFTSOLN", "SOPHIOS", "SPAL", "SPECIALITY",
    "SPSIND", "SREEL", "SRG", "SRIPIPES", "STAR",
    "STARBUSHOR", "SUKHJITS", "SUMIT", "SUNFLAG", "SUPERNOVA",
    "SWASTIKA", "SYNCOM", "SYSTEMIX", "TALWALKARS", "TATAMETALI",
    "TECHNOE", "TECHNOELE", "TGBHOTELS", "THIRUMALAI", "THOMASCOOK",
    "TIMETECHNO", "TJSB", "TRIGYN", "TRIPATHYI", "TUFROPES",
    "TVSELECT", "V2RETAIL", "VARROC", "VSTIND", "VSSL",
    "VVFLTD", "WALCHANNAG", "WEBEL", "WIPIND", "XCHANGING",
    "XTGLOBAL", "ZENTEC", "ZODJRDMKJ", "ZUARIIND", "JKIL",
    "NUVOCO", "ROUTE", "PRAXIS", "PRINCEPIPE", "SOLARINDS",
    "TATAINVEST", "SUPREMEIND", "VGUARD", "VSTIND", "ROLTAS",
    "RAJRATAN", "PUROHIT", "QUESS", "PDMJEPAPER", "PGHH",
]

# ── Additional liquid NSE stocks ──────────────────────────────────────────────
ADDITIONAL_LIQUID: List[str] = [
    "PERSISTENT", "TATATECH", "MANKIND", "JSWENERGY", "CANBK",
    "PNB", "BANKBARODA", "INDIANHOTEL", "GMRINFRA", "SUZLON",
    "IDEA", "RCOM", "TATACHEM", "SAIL", "NHPC",
    "SJVN", "RVNL", "IRFC", "IRCON", "HAL",
    "BEL", "BHEL", "NTPC", "POWERGRID", "GAIL",
    "OIL", "MGL", "IGL", "MAHANAGAR", "TORNTPOWER",
    "TATAPOWER", "JSWENERGY", "ADANIPOWER", "CESC", "NHPC",
    "CRISIL", "MCX", "CDSL", "BSE", "MSEI",
    "ANGELONE", "MOTILALOFS", "IIFL", "5PAISA", "GEOJITFSL",
    "DMART", "NYKAA", "PAYTM", "POLICYBZR", "CARTRADE",
    "EASEMYTRIP", "IXIGO", "INDIAMART", "JUSTDIAL", "MAKEMYTRIP",
    "MAPMYINDIA", "TANLA", "NAZARA", "RATEGAIN", "HAPPSTMNDS",
]

# ── Company metadata: ticker → (name, sector) ─────────────────────────────────
COMPANY_INFO: Dict[str, Tuple[str, str]] = {
    # Nifty 50
    "ADANIENT": ("Adani Enterprises", "Conglomerate"),
    "ADANIPORTS": ("Adani Ports", "Infrastructure"),
    "APOLLOHOSP": ("Apollo Hospitals", "Healthcare"),
    "ASIANPAINT": ("Asian Paints", "Consumer"),
    "AXISBANK": ("Axis Bank", "Banking"),
    "BAJAJ-AUTO": ("Bajaj Auto", "Auto"),
    "BAJAJFINSV": ("Bajaj Finserv", "Financial Services"),
    "BAJFINANCE": ("Bajaj Finance", "NBFC"),
    "BHARTIARTL": ("Bharti Airtel", "Telecom"),
    "BPCL": ("BPCL", "Oil & Gas"),
    "BRITANNIA": ("Britannia Industries", "FMCG"),
    "CIPLA": ("Cipla", "Pharma"),
    "COALINDIA": ("Coal India", "Mining"),
    "DIVISLAB": ("Divi's Laboratories", "Pharma"),
    "DRREDDY": ("Dr. Reddy's Laboratories", "Pharma"),
    "EICHERMOT": ("Eicher Motors", "Auto"),
    "GRASIM": ("Grasim Industries", "Cement"),
    "HCLTECH": ("HCL Technologies", "IT"),
    "HDFCBANK": ("HDFC Bank", "Banking"),
    "HDFCLIFE": ("HDFC Life Insurance", "Insurance"),
    "HEROMOTOCO": ("Hero MotoCorp", "Auto"),
    "HINDALCO": ("Hindalco Industries", "Metals"),
    "HINDUNILVR": ("Hindustan Unilever", "FMCG"),
    "ICICIBANK": ("ICICI Bank", "Banking"),
    "INDUSINDBK": ("IndusInd Bank", "Banking"),
    "INFY": ("Infosys", "IT"),
    "ITC": ("ITC", "FMCG"),
    "JSWSTEEL": ("JSW Steel", "Metals"),
    "KOTAKBANK": ("Kotak Mahindra Bank", "Banking"),
    "LT": ("Larsen & Toubro", "Infrastructure"),
    "M&M": ("Mahindra & Mahindra", "Auto"),
    "MARUTI": ("Maruti Suzuki", "Auto"),
    "NESTLEIND": ("Nestle India", "FMCG"),
    "NTPC": ("NTPC", "Power"),
    "ONGC": ("Oil & Natural Gas Corporation", "Oil & Gas"),
    "POWERGRID": ("Power Grid Corporation", "Power"),
    "RELIANCE": ("Reliance Industries", "Conglomerate"),
    "SBILIFE": ("SBI Life Insurance", "Insurance"),
    "SBIN": ("State Bank of India", "Banking"),
    "SHREECEM": ("Shree Cement", "Cement"),
    "SUNPHARMA": ("Sun Pharmaceutical", "Pharma"),
    "TATACONSUM": ("Tata Consumer Products", "FMCG"),
    "TATAMOTORS": ("Tata Motors", "Auto"),
    "TATASTEEL": ("Tata Steel", "Metals"),
    "TCS": ("Tata Consultancy Services", "IT"),
    "TECHM": ("Tech Mahindra", "IT"),
    "TITAN": ("Titan Company", "Consumer"),
    "ULTRACEMCO": ("UltraTech Cement", "Cement"),
    "UPL": ("UPL", "Agrochemicals"),
    "WIPRO": ("Wipro", "IT"),
    # Nifty Next 50
    "ABB": ("ABB India", "Capital Goods"),
    "ABBOTINDIA": ("Abbott India", "Pharma"),
    "AMBUJACEM": ("Ambuja Cements", "Cement"),
    "AUROPHARMA": ("Aurobindo Pharma", "Pharma"),
    "BANDHANBNK": ("Bandhan Bank", "Banking"),
    "BERGEPAINT": ("Berger Paints", "Consumer"),
    "BIOCON": ("Biocon", "Pharma"),
    "BOSCHLTD": ("Bosch", "Auto Ancillary"),
    "CHOLAFIN": ("Cholamandalam Investment", "NBFC"),
    "COLPAL": ("Colgate-Palmolive", "FMCG"),
    "DABUR": ("Dabur India", "FMCG"),
    "DLF": ("DLF", "Real Estate"),
    "GAIL": ("GAIL India", "Oil & Gas"),
    "GODREJCP": ("Godrej Consumer Products", "FMCG"),
    "GODREJPROP": ("Godrej Properties", "Real Estate"),
    "HAVELLS": ("Havells India", "Consumer"),
    "ICICIGI": ("ICICI Lombard General Insurance", "Insurance"),
    "ICICIPRULI": ("ICICI Prudential Life Insurance", "Insurance"),
    "INDIGO": ("InterGlobe Aviation", "Aviation"),
    "INDUSTOWER": ("Indus Towers", "Telecom"),
    "IOC": ("Indian Oil Corporation", "Oil & Gas"),
    "JINDALSTEL": ("Jindal Steel & Power", "Metals"),
    "JUBLFOOD": ("Jubilant Foodworks", "Consumer"),
    "LUPIN": ("Lupin", "Pharma"),
    "MARICO": ("Marico", "FMCG"),
    "MCDOWELL-N": ("United Spirits", "FMCG"),
    "MFSL": ("Max Financial Services", "Insurance"),
    "MUTHOOTFIN": ("Muthoot Finance", "NBFC"),
    "NAUKRI": ("Info Edge India", "IT"),
    "NMDC": ("NMDC", "Mining"),
    "OFSS": ("Oracle Financial Services", "IT"),
    "PAGEIND": ("Page Industries", "Consumer"),
    "PIIND": ("PI Industries", "Agrochemicals"),
    "PIDILITIND": ("Pidilite Industries", "Chemicals"),
    "RECLTD": ("REC", "NBFC"),
    "SAIL": ("Steel Authority of India", "Metals"),
    "SIEMENS": ("Siemens India", "Capital Goods"),
    "SRF": ("SRF", "Chemicals"),
    "TORNTPHARM": ("Torrent Pharmaceuticals", "Pharma"),
    "TRENT": ("Trent", "Retail"),
    "TVSMOTOR": ("TVS Motor Company", "Auto"),
    "UBL": ("United Breweries", "FMCG"),
    "VEDL": ("Vedanta", "Metals"),
    "VOLTAS": ("Voltas", "Consumer"),
    "ADANIGREEN": ("Adani Green Energy", "Power"),
    "ADANITRANS": ("Adani Transmission", "Power"),
    "BALKRISIND": ("Balkrishna Industries", "Auto Ancillary"),
    "ZOMATO": ("Zomato", "Consumer"),
    "ZEEL": ("Zee Entertainment", "Media"),
    "WHIRLPOOL": ("Whirlpool of India", "Consumer"),
    # Midcap
    "AAVAS": ("Aavas Financiers", "NBFC"),
    "ABCAPITAL": ("Aditya Birla Capital", "Financial Services"),
    "ABFRL": ("Aditya Birla Fashion", "Retail"),
    "ACC": ("ACC", "Cement"),
    "AFFLE": ("Affle India", "IT"),
    "AJANTPHARM": ("Ajanta Pharma", "Pharma"),
    "ALKEM": ("Alkem Laboratories", "Pharma"),
    "APLLTD": ("APL Apollo Tubes", "Metals"),
    "ASTRAL": ("Astral Poly Technik", "Building Materials"),
    "ATUL": ("Atul", "Chemicals"),
    "AUBANK": ("AU Small Finance Bank", "Banking"),
    "BAJAJHFL": ("Bajaj Housing Finance", "NBFC"),
    "BATAINDIA": ("Bata India", "Consumer"),
    "BHARATFORG": ("Bharat Forge", "Auto Ancillary"),
    "BLUESTARCO": ("Blue Star", "Consumer"),
    "BSOFT": ("Birlasoft", "IT"),
    "CAMS": ("CAMS", "Financial Services"),
    "CANFINHOME": ("Can Fin Homes", "NBFC"),
    "CDSL": ("CDSL", "Financial Services"),
    "CESC": ("CESC", "Power"),
    "CHAMBLFERT": ("Chambal Fertilisers", "Chemicals"),
    "CLEAN": ("Clean Science and Technology", "Chemicals"),
    "CONCOR": ("Container Corporation of India", "Logistics"),
    "COROMANDEL": ("Coromandel International", "Agrochemicals"),
    "CROMPTON": ("Crompton Greaves Consumer", "Consumer"),
    "CUMMINSIND": ("Cummins India", "Capital Goods"),
    "DCMSHRIRAM": ("DCM Shriram", "Chemicals"),
    "DEEPAKNTR": ("Deepak Nitrite", "Chemicals"),
    "DELTACORP": ("Delta Corp", "Gaming"),
    "DIXON": ("Dixon Technologies", "Consumer Electronics"),
    "EDELWEISS": ("Edelweiss Financial Services", "Financial Services"),
    "ELGIEQUIP": ("Elgi Equipments", "Capital Goods"),
    "EMAMILTD": ("Emami", "FMCG"),
    "ENDURANCE": ("Endurance Technologies", "Auto Ancillary"),
    "ENGINERSIN": ("Engineers India", "Infrastructure"),
    "EQUITASBNK": ("Equitas Small Finance Bank", "Banking"),
    "EXIDEIND": ("Exide Industries", "Auto Ancillary"),
    "FEDERALBNK": ("Federal Bank", "Banking"),
    "FINEORG": ("Fine Organic Industries", "Chemicals"),
    "FLUOROCHEM": ("Gujarat Fluorochemicals", "Chemicals"),
    "FORTIS": ("Fortis Healthcare", "Healthcare"),
    "GALAXYSURF": ("Galaxy Surfactants", "Chemicals"),
    "GHCL": ("GHCL", "Chemicals"),
    "GNFC": ("Gujarat Narmada Valley Fertilizers", "Chemicals"),
    "GODREJIND": ("Godrej Industries", "Conglomerate"),
    "GRANULES": ("Granules India", "Pharma"),
    "GSFC": ("Gujarat State Fertilizers", "Chemicals"),
    "GSPL": ("GSPL", "Oil & Gas"),
    "GUJGASLTD": ("Gujarat Gas", "Oil & Gas"),
    "HAPPSTMNDS": ("Happiest Minds Technologies", "IT"),
    "HATSUN": ("Hatsun Agro Product", "FMCG"),
    "HDFCAMC": ("HDFC AMC", "Financial Services"),
    "HFCL": ("HFCL", "Telecom"),
    "HIKAL": ("Hikal", "Chemicals"),
    "HINDPETRO": ("Hindustan Petroleum Corporation", "Oil & Gas"),
    "HONAUT": ("Honeywell Automation India", "Capital Goods"),
    "HUDCO": ("Housing and Urban Development Corporation", "NBFC"),
    "IBREALEST": ("Indiabulls Real Estate", "Real Estate"),
    "IDFC": ("IDFC", "Financial Services"),
    "IDFCFIRSTB": ("IDFC First Bank", "Banking"),
    "IEX": ("Indian Energy Exchange", "Financial Services"),
    "IIFL": ("IIFL Finance", "NBFC"),
    "INDHOTEL": ("Indian Hotels Company", "Hotels"),
    "INDIAMART": ("IndiaMART InterMESH", "IT"),
    "INDIANB": ("Indian Bank", "Banking"),
    "IOLCP": ("IOL Chemicals and Pharmaceuticals", "Pharma"),
    "IPCA": ("IPCA Laboratories", "Pharma"),
    "IRCTC": ("Indian Railway Catering and Tourism", "Tourism"),
    "JBCHEPHARM": ("JB Chemicals & Pharmaceuticals", "Pharma"),
    "JKCEMENT": ("JK Cement", "Cement"),
    "JKLAKSHMI": ("JK Lakshmi Cement", "Cement"),
    "JKPAPER": ("JK Paper", "Paper"),
    "JKTYRES": ("JK Tyre & Industries", "Auto Ancillary"),
    "JMFINANCIL": ("JM Financial", "Financial Services"),
    "JUBLINGREA": ("Jubilant Ingrevia", "Chemicals"),
    "KAJARIACER": ("Kajaria Ceramics", "Building Materials"),
    "KALPATPOWR": ("Kalpataru Power Transmission", "Infrastructure"),
    "KANSAINER": ("Kansai Nerolac Paints", "Consumer"),
    "KEC": ("KEC International", "Infrastructure"),
    "KPITTECH": ("KPIT Technologies", "IT"),
    "KRBL": ("KRBL", "FMCG"),
    "LALPATHLAB": ("Dr Lal PathLabs", "Healthcare"),
    "LAURUSLABS": ("Laurus Labs", "Pharma"),
    "LEMONTREE": ("Lemon Tree Hotels", "Hotels"),
    "LICI": ("LIC Housing Finance", "NBFC"),
    "LINDEINDIA": ("Linde India", "Chemicals"),
    "LTTS": ("L&T Technology Services", "IT"),
    "LUXIND": ("Lux Industries", "Textile"),
    "MANAPPURAM": ("Manappuram Finance", "NBFC"),
    "MASFIN": ("MAS Financial Services", "NBFC"),
    "MAXHEALTH": ("Max Healthcare Institute", "Healthcare"),
    "METROPOLIS": ("Metropolis Healthcare", "Healthcare"),
    "MGL": ("Mahanagar Gas", "Oil & Gas"),
    "MINDACORP": ("Minda Corporation", "Auto Ancillary"),
    "MPHASIS": ("Mphasis", "IT"),
    "NATCOPHARM": ("Natco Pharma", "Pharma"),
    "NAVINFLUOR": ("Navin Fluorine International", "Chemicals"),
    "NESCO": ("Nesco", "Real Estate"),
    "NILKAMAL": ("Nilkamal", "Plastics"),
    "OLECTRA": ("Olectra Greentech", "Auto"),
    "ORIENTCEM": ("Orient Cement", "Cement"),
    "PATELENG": ("Patel Engineering", "Infrastructure"),
    "PCBL": ("Phillips Carbon Black", "Chemicals"),
    "PERSISTENT": ("Persistent Systems", "IT"),
    "PFIZER": ("Pfizer India", "Pharma"),
    "PHOENIXLTD": ("Phoenix Mills", "Real Estate"),
    "POLYCAB": ("Polycab India", "Consumer"),
    "POONAWALLA": ("Poonawalla Fincorp", "NBFC"),
    "QUESS": ("Quess Corp", "Services"),
    "RADICO": ("Radico Khaitan", "FMCG"),
    "RAILTEL": ("Railtel Corporation", "Telecom"),
    "RAIN": ("Rain Industries", "Chemicals"),
    "RALLIS": ("Rallis India", "Agrochemicals"),
    "RATNAMANI": ("Ratnamani Metals & Tubes", "Metals"),
    "RAYMOND": ("Raymond", "Textile"),
    "REDINGTON": ("Redington", "IT Distribution"),
    "RELAXO": ("Relaxo Footwears", "Consumer"),
    "RITES": ("RITES", "Infrastructure"),
    "ROUTE": ("Route Mobile", "IT"),
    "SAPPHIRE": ("Sapphire Foods India", "Consumer"),
    "SCHAEFFLER": ("Schaeffler India", "Auto Ancillary"),
    "SEQUENT": ("Sequent Scientific", "Pharma"),
    "SKFINDIA": ("SKF India", "Capital Goods"),
    "SOBHA": ("Sobha", "Real Estate"),
    "SOLARINDS": ("Solar Industries India", "Chemicals"),
    "SPARC": ("Sun Pharma Advanced Research", "Pharma"),
    "SPANDANA": ("Spandana Sphoorty Financial", "NBFC"),
    "STOVEKRAFT": ("Stovekraft", "Consumer"),
    "SUDARSCHEM": ("Sudarshan Chemical Industries", "Chemicals"),
    "SUMICHEM": ("Sumitomo Chemical India", "Agrochemicals"),
    "SUNTV": ("Sun TV Network", "Media"),
    "SUPRAJIT": ("Suprajit Engineering", "Auto Ancillary"),
    "SUPREMEIND": ("Supreme Industries", "Plastics"),
    "SYNGENE": ("Syngene International", "Pharma"),
    "TASTYBITE": ("Tasty Bite Eatables", "FMCG"),
    "TATACHEM": ("Tata Chemicals", "Chemicals"),
    "TATACOMM": ("Tata Communications", "Telecom"),
    "TATAINVEST": ("Tata Investment Corporation", "Financial Services"),
    "TEAMLEASE": ("TeamLease Services", "Services"),
    "THERMAX": ("Thermax", "Capital Goods"),
    "TIMKEN": ("Timken India", "Capital Goods"),
    "TTKPRESTIG": ("TTK Prestige", "Consumer"),
    "TVSSRICHAK": ("TVS Srichakra", "Auto Ancillary"),
    "UJJIVAN": ("Ujjivan Financial Services", "NBFC"),
    "UNIONBANK": ("Union Bank of India", "Banking"),
    "USHAMART": ("Usha Martin", "Metals"),
    "VAIBHAVGBL": ("Vaibhav Global", "Retail"),
    "VARROC": ("Varroc Engineering", "Auto Ancillary"),
    "VGUARD": ("V-Guard Industries", "Consumer"),
    "VMART": ("V-Mart Retail", "Retail"),
    "VSTIND": ("VST Industries", "FMCG"),
    "WOCKPHARMA": ("Wockhardt", "Pharma"),
    "YESBANK": ("Yes Bank", "Banking"),
    "ZYDUSLIFE": ("Zydus Lifesciences", "Pharma"),
    "SOLARA": ("Solara Active Pharma Sciences", "Pharma"),
    "MAITHANALL": ("Maithan Alloys", "Metals"),
    "POLYMED": ("Poly Medicure", "Healthcare"),
    "RPGLIFE": ("RPG Life Sciences", "Pharma"),
    "SANOFI": ("Sanofi India", "Pharma"),
    "MIDHANI": ("Mishra Dhatu Nigam", "Defence"),
    "APOLLOTYRE": ("Apollo Tyres", "Auto Ancillary"),
    "APCOTEX": ("Apcotex Industries", "Chemicals"),
    "CERA": ("Cera Sanitaryware", "Building Materials"),
    "CYIENT": ("Cyient", "IT"),
    "DCBBANK": ("DCB Bank", "Banking"),
    "GLENMARK": ("Glenmark Pharmaceuticals", "Pharma"),
    "GRINDWELL": ("Grindwell Norton", "Capital Goods"),
    "JYOTHYLAB": ("Jyothy Labs", "FMCG"),
    "KPRMILL": ("K.P.R. Mill", "Textile"),
    "MINDA": ("Minda Industries", "Auto Ancillary"),
    "MOTILALOFS": ("Motilal Oswal Financial Services", "Financial Services"),
    "NAVNETEDUL": ("Navneet Education", "Education"),
    "NEOGEN": ("Neogen Chemicals", "Chemicals"),
    "NIITLTD": ("NIIT Learning Systems", "Education"),
    "PRAJIND": ("Praj Industries", "Capital Goods"),
    "PRINCEPIPE": ("Prince Pipes and Fittings", "Building Materials"),
    "RBLBANK": ("RBL Bank", "Banking"),
    "VIMTALABS": ("Vimta Labs", "Healthcare"),
    "INDIGOPNTS": ("Indigo Paints", "Consumer"),
    "SUVENPHAR": ("Suven Pharmaceuticals", "Pharma"),
    # Default for unmapped
}

SECTOR_LIST = sorted(set(v[1] for v in COMPANY_INFO.values()))


def get_universe(category: str = "full") -> List[str]:
    """Return list of tickers (without .NS) for the selected universe."""
    universe_map = {
        "nifty50": NIFTY_50,
        "next50": NIFTY_NEXT_50,
        "midcap150": NIFTY_MIDCAP_150,
        "smallcap250": NIFTY_SMALLCAP_250,
        "full": NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250 + ADDITIONAL_LIQUID,
    }
    raw = universe_map.get(category, NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250 + ADDITIONAL_LIQUID)
    return list(dict.fromkeys(raw))  # deduplicate preserving order


def get_tickers_ns(category: str = "full") -> List[str]:
    """Return tickers with .NS suffix for yfinance."""
    return [f"{t}.NS" for t in get_universe(category)]


def get_company_name(ticker: str) -> str:
    base = ticker.replace(".NS", "")
    return COMPANY_INFO.get(base, (base, "Unknown"))[0]


def get_sector(ticker: str) -> str:
    base = ticker.replace(".NS", "")
    return COMPANY_INFO.get(base, ("Unknown", "Unknown"))[1]


def get_market_cap_category(market_cap: float) -> str:
    """Classify by market cap (INR crores)."""
    if market_cap >= 20000:
        return "Large Cap"
    elif market_cap >= 5000:
        return "Mid Cap"
    return "Small Cap"
